# Generated by Django 5.2.17 on 2026-08-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silver', models.PositiveIntegerField(default=99000)),
                ('gold', models.PositiveIntegerField(default=199000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('silver', 'نقره\u200cای'), ('gold', 'طلایی')], max_length=20)),
                ('months', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'در حال انجام'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=128)),
                ('gateway', models.CharField(default='mock', max_length=40)),
                ('ref_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtistPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('streams', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('settled', 'تسویه شده')], default='pending', max_length=20)),
                ('month', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('artist', 'month'), name='unique_artist_month_payout')],
            },
        ),
    ]
